In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('bigmartsales.csv')

In [6]:
df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [8]:
df[['Item_MRP','Item_Outlet_Sales']].mean()

Item_MRP              140.992782
Item_Outlet_Sales    2181.288914
dtype: float64

In [9]:
df[['Item_MRP','Item_Outlet_Sales']].median()

Item_MRP              143.0128
Item_Outlet_Sales    1794.3310
dtype: float64

mean and median are same then it is symmetric
# left skewed
if mean is less than median then it is left symmetric
# right 

In [16]:
df[['Item_MRP','Item_Outlet_Sales']].mode()
#if your event is occuring again and then we use mode

Item_MRP  Item_Outlet_Sales
0  172.0422            958.752

In [12]:
df[['Item_MRP','Item_Outlet_Sales']].std()

Item_MRP               62.275067
Item_Outlet_Sales    1706.499616
dtype: float64

In [13]:
round(df[['Item_MRP','Item_Outlet_Sales']].var(),2)

Item_MRP                3878.18
Item_Outlet_Sales    2912140.94
dtype: float64

In [15]:
#pip install scipy
#conda ind=stall -c anaconda scipy
from scipy.stats import iqr
iqr(df[['Item_MRP','Item_Outlet_Sales']],axis=0)#here 

array([  91.8172, 2267.049 ])

#business decision steps
#1.calculation of mean and median
#2.calculation of standard deviation and variation
#3.calculation of skewnes
#4.calculation of kurtosis

#Kurtosis is the fourth central moment divided by the square of the variance. If Fisher’s definition is used, then 3.0 is subtracted from the result to give 0.0 for a normal distribution.

In [19]:
from scipy.stats import skew,kurtosis

In [25]:
kurtosis(df[['Item_Outlet_Sales']],fisher=True)

array([1.61422499])

In [26]:
kurtosis(df[['Item_Outlet_Sales']],fisher=False)

array([4.61422499])

In [22]:
skew(df['Item_Outlet_Sales'])

1.177323353967637

In [24]:
#z score
from scipy.stats import zscore
z=np.abs(zscore(df[['Item_MRP','Item_Outlet_Sales']]))
z

Item_MRP  Item_Outlet_Sales
0     1.747454           0.910601
1     1.489023           1.018440
2     0.010040           0.049238
3     0.660050           0.849103
4     1.399220           0.695373
...        ...                ...
8518  1.180783           0.349915
8519  0.527301           0.956402
8520  0.897208           0.579100
8521  0.607977           0.196725
8522  1.052261           0.829594

[8523 rows x 2 columns]